- name: Add PHP repository into sources list
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Install PHP
  apt:
    name: [ 'php{{ php.version }}',
            'php{{ php.version }}-bz2',
            'php{{ php.version }}-cli',
            'php{{ php.version }}-common',
            'php{{ php.version }}-curl',
            'php{{ php.version }}-dev',
            'php{{ php.version }}-fpm',
            'php{{ php.version }}-gd',
            'php{{ php.version }}-intl',
            'php{{ php.version }}-json',
            'php{{ php.version }}-ldap',
            'php{{ php.version }}-mbstring',
            'php{{ php.version }}-mysql',
            'php{{ php.version }}-odbc',
            'php{{ php.version }}-opcache',
            'php{{ php.version }}-readline',
            'php{{ php.version }}-sqlite3',
            'php{{ php.version }}-xml',
            'php{{ php.version }}-xsl',
            'php{{ php.version }}-zip',
    ]
    state: present
    update_cache: yes